baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hamilton Taveras'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 2