baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hamilton Taveras'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Blog"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "other"
    name = "CV"
    url = "https://www.dropbox.com/scl/fi/467fps43b970p9o5l7qf8/Hamilton_Taveras_-_Economist_Spanish_April2024.pdf?rlkey=dikx3i9plpt7bv2av2wpjp0do&st=y9o0owmy&dl=0"
    weight = 2