// CMP-SEARCH. Pagefind query + filter state. Pagefind's runtime bundle only
// exists after `pagefind --site dist` runs (TECH-SEARCH-001), so it is
// always loaded dynamically at runtime, never imported at build time.
import { useEffect, useRef, useState } from "react";

type Status = "idle" | "loading" | "results" | "empty" | "error";

interface PagefindResultData {
  url: string;
  meta: { title?: string };
  excerpt: string;
}
interface PagefindResult {
  data: () => Promise<PagefindResultData>;
}
interface PagefindApi {
  options?: (options: { baseUrl?: string; basePath?: string }) => Promise<void>;
  search: (query: string, options?: Record<string, unknown>) => Promise<{ results: PagefindResult[] }>;
}

interface Props {
  language: "en" | "es";
  placeholder: string;
  idleLabel: string;
  loadingLabel: string;
  emptyLabel: string;
  errorLabel: string;
  resultLabelOne: string;
  resultLabelMany: string;
}

export default function Search({ language, placeholder, idleLabel, loadingLabel, emptyLabel, errorLabel, resultLabelOne, resultLabelMany }: Props) {
  const [status, setStatus] = useState<Status>("idle");
  // Always starts at "" so the first client render matches the
  // server-rendered markup exactly (a lazy initializer that branches on
  // `typeof window` produces a hydration mismatch, since it runs once
  // during SSR and again on the client with a different result).
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<{ url: string; title: string; excerpt: string }[]>([]);
  const pagefindRef = useRef<PagefindApi | null>(null);

  // Client-only: adopt ?q= from the URL after mount, once hydration has
  // already reconciled against the SSR-safe initial state above.
  useEffect(() => {
    const initial = new URLSearchParams(window.location.search).get("q");
    if (initial) setQuery(initial);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    let cancelled = false;
    async function ensurePagefind() {
      if (pagefindRef.current) return pagefindRef.current;
      try {
        // Pagefind's runtime bundle is generated by `pagefind --site dist`
        // after `astro build`, so it cannot exist as a resolvable module at
        // bundle time. The path is built from parts at runtime so Rollup
        // never sees a literal specifier to resolve during the build.
        const pagefindPath = `${import.meta.env.BASE_URL}pagefind/pagefind.js`;
        const mod = (await import(/* @vite-ignore */ pagefindPath)) as PagefindApi;
        await mod.options?.({
          baseUrl: import.meta.env.BASE_URL,
          basePath: `${import.meta.env.BASE_URL}pagefind/`
        });
        if (!cancelled) pagefindRef.current = mod;
        return mod;
      } catch {
        return null;
      }
    }

    async function run() {
      const params = new URLSearchParams(window.location.search);
      if (query) params.set("q", query);
      else params.delete("q");
      window.history.replaceState({}, "", `${window.location.pathname}${params.toString() ? `?${params}` : ""}`);

      if (!query) {
        setStatus("idle");
        setResults([]);
        return;
      }
      setStatus("loading");
      const pagefind = await ensurePagefind();
      if (cancelled) return;
      if (!pagefind) {
        setStatus("error");
        return;
      }
      try {
        const search = await pagefind.search(query, { filters: { language } });
        if (cancelled) return;
        const data = await Promise.all(search.results.slice(0, 20).map((r) => r.data()));
        if (cancelled) return;
        setResults(data.map((d) => ({ url: d.url, title: d.meta.title ?? d.url, excerpt: d.excerpt })));
        setStatus(data.length > 0 ? "results" : "empty");
      } catch {
        if (!cancelled) setStatus("error");
      }
    }
    run();
    return () => {
      cancelled = true;
    };
  }, [query, language]);

  return (
    <div className="search">
      <label className="visually-hidden" htmlFor="search-input">{placeholder}</label>
      <input
        id="search-input"
        type="search"
        value={query}
        placeholder={placeholder}
        onChange={(e) => setQuery(e.target.value)}
        className="search__input"
      />

      <p role="status" aria-live="polite" className="text-small">
        {status === "idle" && idleLabel}
        {status === "loading" && loadingLabel}
        {status === "results" && `${results.length} ${results.length === 1 ? resultLabelOne : resultLabelMany}`}
        {status === "empty" && emptyLabel}
        {status === "error" && errorLabel}
      </p>

      {status === "results" && (
        <ul className="search__results">
          {results.map((r) => (
            <li key={r.url}>
              <a href={r.url}>
                <span className="text-body-l">{r.title}</span>
                <span className="text-small" dangerouslySetInnerHTML={{ __html: r.excerpt }} />
              </a>
            </li>
          ))}
        </ul>
      )}

      <style
        dangerouslySetInnerHTML={{
          __html: `
        .search__input { width: 100%; max-width: 480px; padding: var(--space-3); border: var(--border-strong); border-radius: var(--radius-small); font-size: var(--size-body-l); }
        .search__results { display: flex; flex-direction: column; gap: var(--space-4); margin-top: var(--space-4); }
        .search__results a { display: flex; flex-direction: column; gap: var(--space-1); border-top: var(--border-hairline); padding-top: var(--space-3); }
      `
        }}
      />
    </div>
  );
}
